/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam;

import java.util.Date;
import javax.swing.*;
import java.time.*;
/**
 *
 * @author Brandon Shi
 */
public class AddExamFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddExamFrame
     */
    public MainFrame prevFrame;//This stores the frame before so that this AddExamFrame can transfer data back to it
    
    
    public AddExamFrame(MainFrame p) {
        //The previous frame is added as a parameter
        prevFrame = p;
        initComponents();
        accommodationComboBox.setVisible(false);//Set the accomodationComboBox invisible, until the accommodationRadioButton is clicked
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addExamPanel = new javax.swing.JPanel();
        examNameLabel = new javax.swing.JLabel();
        addExamToolBar = new javax.swing.JToolBar();
        toolBarPanel = new javax.swing.JPanel();
        addExamLabel = new javax.swing.JLabel();
        examNameTextField = new javax.swing.JTextField();
        examTimeLabel = new javax.swing.JLabel();
        examTimeSpinner = new javax.swing.JSpinner();
        examLengthLabel = new javax.swing.JLabel();
        examLengthTextField = new javax.swing.JTextField();
        accommodationRadioButton = new javax.swing.JRadioButton();
        accommodationComboBox = new javax.swing.JComboBox<>();
        addExamButtonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        addExamPanel.setBackground(new java.awt.Color(0, 0, 51));
        addExamPanel.setPreferredSize(new java.awt.Dimension(540, 360));

        examNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        examNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        examNameLabel.setText("Enter a new exam:");

        addExamToolBar.setBackground(new java.awt.Color(51, 0, 153));
        addExamToolBar.setBorder(null);
        addExamToolBar.setFloatable(false);
        addExamToolBar.setRollover(true);

        toolBarPanel.setBackground(new java.awt.Color(51, 0, 153));

        addExamLabel.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        addExamLabel.setForeground(new java.awt.Color(255, 255, 255));
        addExamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addExamLabel.setText("Add a new Exam");
        addExamLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addExamLabelComponentShown(evt);
            }
        });

        javax.swing.GroupLayout toolBarPanelLayout = new javax.swing.GroupLayout(toolBarPanel);
        toolBarPanel.setLayout(toolBarPanelLayout);
        toolBarPanelLayout.setHorizontalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(addExamLabel)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        toolBarPanelLayout.setVerticalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(addExamLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addExamToolBar.add(toolBarPanel);

        examNameTextField.setBackground(new java.awt.Color(0, 0, 102));
        examNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        examNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        examNameTextField.setText("Default Exam");
        examNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examNameTextFieldActionPerformed(evt);
            }
        });

        examTimeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        examTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        examTimeLabel.setText("Enter start time:");

        examTimeSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        examTimeSpinner.setModel(new javax.swing.SpinnerDateModel());

        examLengthLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        examLengthLabel.setForeground(new java.awt.Color(255, 255, 255));
        examLengthLabel.setText("Enter exam length:");

        examLengthTextField.setText("Example: 2:00");
        examLengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examLengthTextFieldActionPerformed(evt);
            }
        });

        accommodationRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        accommodationRadioButton.setText("Accommodation");
        accommodationRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                accommodationRadioButtonStateChanged(evt);
            }
        });
        accommodationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accommodationRadioButtonActionPerformed(evt);
            }
        });

        accommodationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "25%", "50%" }));
        accommodationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accommodationComboBoxActionPerformed(evt);
            }
        });

        addExamButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/folder/addExam.png"))); // NOI18N
        addExamButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addExamButtonLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addExamButtonLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addExamButtonLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout addExamPanelLayout = new javax.swing.GroupLayout(addExamPanel);
        addExamPanel.setLayout(addExamPanelLayout);
        addExamPanelLayout.setHorizontalGroup(
            addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addExamToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addExamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addExamPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examNameTextField)
                            .addComponent(examTimeSpinner)))
                    .addGroup(addExamPanelLayout.createSequentialGroup()
                        .addGroup(addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addExamPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(examLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addExamPanelLayout.createSequentialGroup()
                                .addComponent(accommodationRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accommodationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addExamPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(addExamButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addExamPanelLayout.setVerticalGroup(
            addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addExamPanelLayout.createSequentialGroup()
                .addComponent(addExamToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examLengthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accommodationRadioButton)
                    .addComponent(accommodationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(addExamButtonLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addExamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addExamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addExamLabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addExamLabelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_addExamLabelComponentShown

    private void examNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examNameTextFieldActionPerformed

    private void examLengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examLengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examLengthTextFieldActionPerformed

    private void accommodationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accommodationRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accommodationRadioButtonActionPerformed

    private void accommodationRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_accommodationRadioButtonStateChanged
        // TODO add your handling code here:
        accommodationComboBox.setVisible(!accommodationComboBox.isVisible());//Change the state of the accommodationComboBox to the opposite(visible to invisible and vice versa).
    }//GEN-LAST:event_accommodationRadioButtonStateChanged

    private void addExamButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamButtonLabelMouseEntered
        // TODO add your handling code here:
        addExamButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/folder/addExamHovered.png")));
    }//GEN-LAST:event_addExamButtonLabelMouseEntered

    private void addExamButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamButtonLabelMouseExited
        // TODO add your handling code here:
        addExamButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/folder/addExam.png")));
    }//GEN-LAST:event_addExamButtonLabelMouseExited

    private void addExamButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamButtonLabelMouseClicked
        /*
           The goal of this function is to collect user inputs, 
           formating them to the correct format that Exam class 
           requires, and make add new Exam object into the MainFrame
        */

        //When the addExamButton is clicked:
        //Changed the icon to a darker version
        addExamButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/folder/addExamClicked.png")));
        
        //Store the exam name in a String variable
        String examName = examNameTextField.getText();
        
        //First take in the exam length as a buffer String. Since the length of the exam is inputed in a simple text field, there is a possibility that the user input wrong information, thus need to be handled
        String examLengthBuffer = examLengthTextField.getText();
     
        //A try-catch block is implemented in case the user inputed wrong data.
        try{
            //If capable, parse the user's input of exam length into two seperate integers, stored in hours and minutes
            String[] splitResult = examLengthBuffer.split(":");//Split the input string on the ":" so that hours and minutes are seperated
            int hours = Integer.parseInt(splitResult[0]);//The hours is the first element in the spilted array
            int mins = Integer.parseInt(splitResult[1]);//The minutes is the second element in the spilted array
            int examLength = hours*60+mins;//The length is in minutes, so it is hours*60+minutes
            
            
            String accommodationOption = (String)accommodationComboBox.getSelectedItem();//Get the selected option from 0%, 10%. 25% and 50%
            double accommodationRatio = Double.parseDouble(accommodationOption.substring(0,accommodationOption.length()-1))/100;//Omit the last character from the ComboBoxOption, which is "%", then parse the percentage into a ratio like 0.25.
            
            //Get the start time of the exam from the spinner. It is a Date object, so convert it to LocalTime using Instant class
            Date time = (Date)examTimeSpinner.getValue();
            Instant instant = Instant.ofEpochMilli(time.getTime());
            LocalTime examTime = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalTime();
            
            Exam exam = new Exam(examName,examLength,examTime,accommodationRatio);//Make an exam object from user's inputs
            prevFrame.addExam(exam);//Call the addExam() method in the previous frame
            
            this.dispose();//Dismiss this frame
        }catch(NumberFormatException e){
            //If there is an exception, show a messahe dialog explaining the situation. Then, reset the examLengthBuffer
            JOptionPane.showMessageDialog(null, "Wrong exam length, please input in the form Hour:Minutes");
            examLengthBuffer = "";
        }
    }//GEN-LAST:event_addExamButtonLabelMouseClicked

    private void accommodationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accommodationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accommodationComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /*//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddExamFrame(prevFrame).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accommodationComboBox;
    private javax.swing.JRadioButton accommodationRadioButton;
    private javax.swing.JLabel addExamButtonLabel;
    private javax.swing.JLabel addExamLabel;
    private javax.swing.JPanel addExamPanel;
    private javax.swing.JToolBar addExamToolBar;
    private javax.swing.JLabel examLengthLabel;
    private javax.swing.JTextField examLengthTextField;
    private javax.swing.JLabel examNameLabel;
    private javax.swing.JTextField examNameTextField;
    private javax.swing.JLabel examTimeLabel;
    private javax.swing.JSpinner examTimeSpinner;
    private javax.swing.JPanel toolBarPanel;
    // End of variables declaration//GEN-END:variables
}